### ISSUE TITLE
Nechť (Ω,P)  je diskrétní pravděpodobnostní prostor a |Ω|≥2 . Pak určitě platí

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-ag1-rozstrel#10]
<img width="861" alt="necht p je diskretni pravdepodobnostni prostor a 2 pak urcite plati" src="https://user-images.githubusercontent.com/9153692/35133076-956d823e-fcce-11e7-9ba7-ef51c5fb1c2c.png">

**Comment by jstorm31** [comment]
Součet P(w) pro všechny w z Omega = 1.
T (takový prvek určitě existuje)
T
F (nemůže být roven jedné, protože v Omega jsou alespoň dva prvky a dohromady musí mít pravděpodobnost 1)
F

**Comment by MSKL** [comment]
takže nemůže existovat prvek pro kterej je P(w) = 1? proč?

**Comment by jstorm31** [comment]
Protože tam je >= 2 w-ček. A v součtu musí dávat 1. Koukni na slide s definicí diskrétního pravděpodobnostního prostoru.

**Comment by MSKL** [comment]
Jasně, ale proč nemůže mít jeden P(a) = 0 a druhej P(b) = 1?
Koukal jsem na to, ale pořád nevidím, proč.

**Comment by MSKL** [comment]
správně je myslím
T - protože jsou dva, musí být alespoň jeden <1
F - protože jsou dva tak alespoň 1 bude >1
T - tohle je true
F - tohle je BS
:)
