### ISSUE TITLE
Násobíme dvě 32-ciferná čísla. Kolik násobení jednociferných čísel proběhne, pokud je vynásobíme školním způsobem a kolik násobení proběhne, pokud je vynásobíme rychlejším způsobem z přednášky?

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-ag1-rozstrel#11]
<img width="862" alt="nasobime dve 32-ciferna cisla kolik nasobeni jednocifernych cisel probehne pokud je vynasobime skolnim zpusobem a kolik nasobeni probehne pokud je vynasobime rychlejsim zpusobem z prednasky" src="https://user-images.githubusercontent.com/9153692/35174259-059e0b8c-fd6f-11e7-89c0-ec9d5fa559ab.png">

**Comment by jstorm31** [comment]
Ze stromu rekurzivního volání. Karacuba rozděluje problémy na 3 podproblémy. Takže násobí postupně: 1, 3, 9, 27, 81, **243**. Počet hladin je log(32) = 5 (na 5. hladině násobí 1-ciferná čísla).

**Comment by MSKL** [comment]
<img width="862" alt="nasobime dve 32-ciferna cisla kolik nasobeni jednocifernych cis" src="https://user-images.githubusercontent.com/9153692/35199809-b4356b3c-ff03-11e7-97d2-ec197eb8c3e1.png">
