### ISSUE TITLE
Necht g v e je libovolny souvisly neorientovany graf jehoz hranam jsou prirazeny vahy ne nutne ruzne z nasledujicich tvrzeni o kostrach tohoto grafu vyberte vsechna pravdiva

### ISSUE THREAD

**Issue by jstorm31** [MSKL/fit-bi-ag1-rozstrel#12]
Skoro všechno špatně 😄. Neumíš vysvětlit?

1. Snad protože jich může být víc a ne všechny musí být v kostře?
2. nechápu
3. jaký je protipříklad?
4. jenom tip, protipříklad? 😄 

![necht g v e je libovolny souvisly neorientovany graf jehoz hranam jsou prirazeny vahy ne nutne ruzne z nasledujicich tvrzeni o kostrach tohoto grafu vyberte vsechna pravdiva](https://user-images.githubusercontent.com/16023539/35174886-4a4afb62-fd71-11e7-90bb-1303526507d6.jpg)

**Comment by MSKL** [comment]
1. může jich tam být více minimálních...?
2. je souvislý a není strom => je tam cyklus; ten ale nemusí být nutně přes hranu e (t může vést třeba k listu) tudíž ji v takovým případě nemůžeš vynechat
3. tyjo chvíli mi dalo to vymyslet 😅 
![graf](https://user-images.githubusercontent.com/9153692/35175947-830cad7e-fd76-11e7-8c95-96d9bccfb8fd.jpg)
4. ne vždycky. může tam být další menší

**Comment by jstorm31** [comment]
Dobře ty 👍
