### ISSUE TITLE
Kolik skoromediánů obsahuje posloupnost dvaceti čísel 2, 8, 11, 6, 13, 12, 12, 7,…

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-ag1-rozstrel#13]
<img width="859" alt="kolik skoromedianu obsahuje posloupnost dvaceti cisel 2 8 11 6 13 12 12 7" src="https://user-images.githubusercontent.com/9153692/35175371-aaa82492-fd73-11e7-92e3-c491e027533c.png">

**Comment by jstorm31** [comment]
Myslím, že by to mohlo být takto.

Do skoromediánu určitě patří prostřední polovina:
12, 12, 7, 14, 12, 15, 13, 6, 10, 6

K tomu přičteš čísla, která už jsou obsáhlé v prostřední polovině, ale vyskytují se i mimo. Tady se jedná o 6. Má výskyt uprostřed, ale i 4 další výskyty mimo:
2, 8, 11, **6**, 13 | 12, 12, 7, 14, 12, 15, 13, 6, 10, 6 | 1, **6**, 9, **6**, **6** 

**Celkem tedy 10 (uprostřed) + 4 (další výskyty 6 mimo) = 14**.

**Comment by MSKL** [comment]
„skoromedián“: prvek, který leží kdekoli v prostředních dvou  čtvrtinách se seřazené posloupnosti.
seřazené = [1, 2, 6, 6, 6, 6, 6, 6, 7, 8, 9, 10, 11, 12, 12, 12, 13, 13, 14, 15]

**Comment by MSKL** [comment]
takže prostřední polovina = [6, 6, 6, 7, 8, 9, 10, 11, 12, 12] + to co přesahuje = [6, 6, 6] + [12] 
to je celkem 14 😄 Vychází to stejně jak jak jsi to dělal ty, ale nevím, jestli to byl dobrej postup úplně

**Comment by jstorm31** [comment]
Aha, takze ta posloupnost musi byt serazena?

**Comment by MSKL** [comment]
tak to je ze zadání
