### ISSUE TITLE
Co lze říci o nejkratší cestě a nejkratším sledu z vrcholu 1 do vrcholu 8 v následujícím grafu?

### ISSUE THREAD

**Issue by jstorm31** [MSKL/fit-bi-ag1-rozstrel#14]
Vyšlo mi, že je delký 3...

![screen shot 2018-01-20 at 01 08 44](https://user-images.githubusercontent.com/16023539/35177300-7b6a8e76-fd7e-11e7-9d14-5ae491405414.jpg)

**Comment by MSKL** [comment]
nejkratší sled neexistuje, je tam zápornej cyklus :)

**Comment by MSKL** [comment]
takže asi FFTT

**Comment by jstorm31** [comment]
Ahaa, diky 😉
