### ISSUE TITLE
Pro následující kód vyberte z nabízených možností všechny, které vyjadřují jeh…

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-ag1-rozstrel#15]
<img width="864" alt="pro nasledujici kod vyberte z nabizenych moznosti vsechny ktere vyjadruji jeh" src="https://user-images.githubusercontent.com/9153692/35178418-0986bb8a-fd89-11e7-8487-461915c6bacd.png">

**Comment by jstorm31** [comment]
Myslim, ze n^3/2

**Comment by MSKL** [comment]
jo, tak to má být, ale proč?

vnější cyklus se zavolá N/3 krát a vnitřní bude N^2

**Comment by jstorm31** [comment]
Jo, myslím, že je to tak.

**Comment by MSKL** [comment]
už to vidím.. vnější n-krát, vnitřní sqrt(n) krát
