### ISSUE TITLE
Hledáme délky nejkratších cest z vrcholu a  v následujícím grafu algoritmem R…

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-ag1-rozstrel#2]
<img width="861" alt="hledame delky nejkratsich cest z vrcholu a v nasledujicim grafu algoritmem r" src="https://user-images.githubusercontent.com/9153692/35125175-ee800b4c-fca8-11e7-8ba7-759f19ee5fce.png">
Já asi ani nějak nechápu zadání

**Comment by MSKL** [comment]
<img width="863" alt="hledame delky nejkratsich cest z vrcholu f v nasledujicim grafu algoritmem relaxace z prednasky na zacatku polozime pro vsechny vrcholy h v a oznacime je jako nenalezene" src="https://user-images.githubusercontent.com/9153692/35178530-923b3b6c-fd8a-11e7-9e7f-59bdec36edcc.png">

**Comment by jstorm31** [comment]
Snad už jsem to trochu pochopil a neříkám úplnou blbost.

**1. příklad**
První je třeba najíd pořadí relaxace vrcholů, které dává nejkratší cesty do všech. To je _a, d, e, b_. A protože už takhle to má 4 vrcholy a jinak to nejde, je jenom 1 možnost.
Odpověď: **1, a, d, e, b**.

**2. příklad**
Relaxace vrcholů pro nejkratší cesty je f, b, c. Zbývá kombinovat s nějakým dalším vrcholem, ale vždy tam musí být v nějakém pořadí f, b, c. Takže možnosti: _fbce, fbdc, fabc, fbac, fbca, fbcd_. 
Odpověď: **6, f, b, c, a**.

**Comment by MSKL** [comment]
vojta mi to dneska asi půl hodiny vysvětloval, tak to trochu chápu. Ale je to těžký 🗡
