### ISSUE TITLE
Maximální binomiální halda/ Vypište posloupnost hodnot (klíčů) uložených v kořenech stromů T binomiální haldy, která vznikne slitím BHMerge

### ISSUE THREAD

**Issue by jstorm31** [MSKL/fit-bi-ag1-rozstrel#20]
![maximalni binomialni halda vypiste posloupnost hodnot klicu ulozenych v korenech stromu t binomialni haldy ktera vznikne slitim bhmerge](https://user-images.githubusercontent.com/16023539/35199507-241c1e64-feff-11e7-8665-49190112756b.png)

Vyšlo mi: budu mít bin. stromy řádu 3 a 4. První kořen 10, druhý 7. Nenakreslis bys mi prosím, jak to má vypadat, ať vím, co dělám blbě?

**Comment by MSKL** [comment]
to řešení je blbě

**Comment by MSKL** [comment]
mělo by to být 10, 7

**Comment by MSKL** [comment]
vyšlo mi to úplně stejně..

**Comment by jstorm31** [comment]
Aha 😄

**Comment by MSKL** [comment]
respektive já nevim, ale prostě nechápu co bychom dělali blbě..
