### ISSUE TITLE
Kolik topologických uspořádání má graf na obrázku?

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-ag1-rozstrel#3]
<img width="863" alt="kolik topologickych usporadani ma graf na obrazku" src="https://user-images.githubusercontent.com/9153692/35125221-1a391e36-fca9-11e7-9bc3-599835bc25d1.png">

**Comment by MSKL** [comment]
<img width="861" alt="kolik topologickych usporadani ma graf na obrazku" src="https://user-images.githubusercontent.com/9153692/35173738-d0d1aece-fd6c-11e7-828e-8bba6c15d974.png">

**Comment by MSKL** [comment]
správně má být 252..
Už to vidím
![sken kopie](https://user-images.githubusercontent.com/9153692/35174105-69d03874-fd6e-11e7-8b84-ff88bd1bdd5d.jpg)

**Comment by jstorm31** [comment]
Nesnáším tady ten typ úloh! 😆
