### ISSUE TITLE
Je daná binomiální halda s 2017  prvky. Vypište postupně posloupnost dvojic Řád:PočetVrcholů na 4. hladině

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-ag1-rozstrel#4]
<img width="863" alt="je dana binomialni halda s 2017 prvky vypiste postupne posloupnost dvojic radpocetvrcholu na 4 hladine" src="https://user-images.githubusercontent.com/9153692/35126696-dbe5f54a-fcae-11e7-906e-27368a82c8ab.png">

**Comment by MSKL** [comment]
<img width="861" alt="je dana binomialni halda s 2017 prvky vypiste postupne posloupnost dvojic rad" src="https://user-images.githubusercontent.com/9153692/35126866-a6244ae6-fcaf-11e7-83d9-ad2094b7b72a.png">

**Comment by MSKL** [comment]
<img width="861" alt="binomialni halda vypiste pocty prvku na 2 hladine v hloubce 2 stromu binomialni haldy" src="https://user-images.githubusercontent.com/9153692/35130703-9622224a-fcc2-11e7-88dc-a23220c01abf.png">

**Comment by jstorm31** [comment]
Tohle se dělá nějak, že si vypíšeš hladiny a řády bin. haldy do tabulky a vyplňuješ postupně počty. Je to podobné jako v Pascalově trojúhelníku. Ale už si to nepamatuju přesně 😄

**Comment by MSKL** [comment]
<img width="862" alt="je dana binomialni halda s 2016 prvky vypiste pocty vrcholu na 3 hladine u j" src="https://user-images.githubusercontent.com/9153692/35178199-c6591b8e-fd86-11e7-9bd3-04ed9b722021.png">
Nejdříve je potřeba spočítat jaké stromy tam budou obsažené (indexování začíná od 0!) a pak kompinačním číslem kCn zjistím počet v n-té hladině k-tého stromu. Hladiny jsou taky indexovaný od nuly.
