### ISSUE TITLE
Kolik nejvíce (neprázdných) hladin může mít AVL strom s 2017  vrcholy?

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-ag1-rozstrel#6]
<img width="863" alt="kolik nejvice neprazdnych hladin muze mit avl strom s 2017 vrcholy" src="https://user-images.githubusercontent.com/9153692/35126849-8b85b346-fcaf-11e7-8f61-e09630002fb7.png">

**Comment by MSKL** [comment]
23 to není
<img width="863" alt="snimek obrazovky 2018-01-19 v 4 05 33" src="https://user-images.githubusercontent.com/9153692/35132949-0b15b11a-fcce-11e7-91d0-5e13c93ca4d3.png">

**Comment by jstorm31** [comment]
Dela se to myslim tim rekurentnim predpisem, co je v prednasce.vyslo mi 14, ale taky blbe 😄. Tak mozna 15?

**Comment by MSKL** [comment]
<img width="865" alt="snimek obrazovky 2018-01-21 v 5 13 40" src="https://user-images.githubusercontent.com/9153692/35190764-f215da1c-fe69-11e7-992b-d251de1bbb42.png">

**Comment by MSKL** [comment]
můžeš mi vysvětlit jak jsi na to přišel? :)

**Comment by jstorm31** [comment]
Podle důkazu věty v přednášce 6, slide 20. Rekurentní předpis pro minimální počet vrcholů na hladině h je A_h = A_h-1 + A_h-2 + 1. Takže:
A_0 = 1
A_1 = 2
A_2 = 4
A_3 = 7
A_5 = 20
A_6 = 33
A_7 = 54
A_8 = 87
A_9 = 142
A_10 = 230
A_11 = 373
A_12 = 604
A_13 = 978
A_14 = 1583
A_15 = 2572

Podle tohohle mi to stále vychází 14 a nevím, kde je chyba a proč to má být 15. A_15 = 2572 je minimum vrcholů potřebných k AVL stromu o hloubce 15 a protože 2017 < 2572, tak by ten strom neměl mít 15 hladin. Možná třeba tohle budeš vědět. 

Jinak v tom důkazu je i odhad A_h = c^h pro c = sqrt(2), ale když uděláš log_c(2017), tak ti vyjde nějak 21, takže ten odhad je hodně hrubý a nejde to takto.

**Comment by jstorm31** [comment]
Už jsem na to přišel. 

> ...AVL strom o n vrcholech může mít nejvýše 1 + log_c(n) hladin.

Takže 1 + log_c(2017) = 1 + 14 = 15. A místo toho logaritmování si spočítat ten rekurentní předpis pro A_h pro maximální hladinu, která nepřesáhne 2017 prvků (tedy 14).
