### ISSUE TITLE
Určete počet všech <různá zadání> podgrafů grafu K3 .

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-ag1-rozstrel#8]
<img width="862" alt="urcete pocet vsech souvislych neizomorfnich podgrafu grafu k3" src="https://user-images.githubusercontent.com/9153692/35128604-d0cd3066-fcb7-11e7-81b8-1027bb05a208.png">
<img width="867" alt="urcete pocet vsech souvislych podgrafu grafu k3" src="https://user-images.githubusercontent.com/9153692/35128612-daea8792-fcb7-11e7-8828-aeeac6ccca0a.png">

**Comment by MSKL** [comment]
souvislých neizomorfních (zapmněl jsem asi na K3):
1 = K3
1 = 2H, 3V
1 = 1H, 2V
1 = 1V
celkem 4

**Comment by jstorm31** [comment]
Jo, souhlasím s těmi komenty. Akorát, počítá se i prazdný podgraf? Protože podle definice by to šlo... Prázdná podmnožina je podmnožina jakékoliv množiny.

**Comment by MSKL** [comment]
z definice grafu: V je neprázdná množina vrcholů.. 👍
