### ISSUE TITLE
Kolik nejvíce komponent souvislosti může mít graf s 21 vrcholy a 73 hranami?

### ISSUE THREAD

**Issue by MSKL** [MSKL/fit-bi-ag1-rozstrel#9]
Bože, já dělám hovadiny 👎 
<img width="863" alt="kolik nejvice komponent souvislosti muze mit graf s 21 vrcholy a 73 hranami" src="https://user-images.githubusercontent.com/9153692/35128648-049dbd66-fcb8-11e7-84c8-351babb6b82f.png">

**Comment by jstorm31** [comment]
1 x K_13 (vleze se do něj až 78 hran, tak je tam dám všechny)
8 x samostatný vrchol
**Celkem 9**??

**Comment by MSKL** [comment]
Jasně, myslím, že jsem zapomněl vydělit počet hran v úplným grafu 2 :)
